image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.4"
  pullPolicy: IfNotPresent

service:
  port: 8080

env:
  password: MYPASSWORD

ingress:
  enabled: true
  host: localhost
  path: /counter
